/**
 * CSRF Token Protection
 * Server-side generation and validation for POST/PUT/DELETE requests
 */

import { cookies } from 'next/headers'
import { NextRequest } from 'next/server'

const CSRF_TOKEN_NAME = 'csrf-token'
const CSRF_HEADER_NAME = 'x-csrf-token'
const TOKEN_EXPIRY_MS = 24 * 60 * 60 * 1000 // 24 hours

/**
 * Generate a CSRF token
 * Returns a token that should be stored in a secure httpOnly cookie
 */
export function generateCSRFToken(): string {
  const randomBytes = new Uint8Array(32)
  crypto.getRandomValues(randomBytes)
  return Array.from(randomBytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

/**
 * Store CSRF token in secure cookie
 */
export async function setCSRFTokenCookie(token: string): Promise<void> {
  const cookieStore = await cookies()
  cookieStore.set(CSRF_TOKEN_NAME, token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'strict',
    maxAge: TOKEN_EXPIRY_MS / 1000,
    path: '/',
  })
}

/**
 * Get CSRF token from cookie
 */
export async function getCSRFToken(): Promise<string | undefined> {
  const cookieStore = await cookies()
  return cookieStore.get(CSRF_TOKEN_NAME)?.value
}

/**
 * Validate CSRF token from request
 * This should be called for POST/PUT/DELETE/PATCH requests
 */
export async function validateCSRFToken(req: NextRequest): Promise<boolean> {
  // Get token from header (client sends this)
  const headerToken = req.headers.get(CSRF_HEADER_NAME)

  if (!headerToken) {
    console.warn('No CSRF token in request header')
    return false
  }

  // Get token from cookie (generated by server)
  const cookieStore = await cookies()
  const cookieToken = cookieStore.get(CSRF_TOKEN_NAME)?.value

  if (!cookieToken) {
    console.warn('No CSRF token in cookie')
    return false
  }

  // Tokens must match
  if (headerToken !== cookieToken) {
    console.warn('CSRF token mismatch')
    return false
  }

  return true
}

/**
 * Middleware to validate CSRF for state-changing requests
 */
export async function withCSRFValidation(req: NextRequest): Promise<boolean> {
  // Only validate for state-changing methods
  const method = req.method.toUpperCase()
  const stateChangingMethods = ['POST', 'PUT', 'DELETE', 'PATCH']

  if (!stateChangingMethods.includes(method)) {
    return true // Skip CSRF validation for GET/HEAD/OPTIONS
  }

  // Skip for public endpoints (opt-in basis)
  const skipCSRFPaths = [
    '/api/auth/signin',
    '/api/auth/signup',
    '/api/auth/forgot-password',
  ]

  const pathname = req.nextUrl.pathname
  if (skipCSRFPaths.some((path) => pathname.startsWith(path))) {
    return true
  }

  return await validateCSRFToken(req)
}

/**
 * Get CSRF token endpoint response
 * This endpoint should be called by the client to get a fresh token
 */
export async function getCSRFTokenResponse() {
  const token = generateCSRFToken()
  await setCSRFTokenCookie(token)
  return token
}
